### ISSUE TITLE
Online Status Indicator under Bot name 

### ISSUE THREAD

**Issue by git-under** [ViNo-community/nano_node_bot#3]
A push feature request, to show the status of the bot under its name will look great and function as a quick indicator to node health something like ---node online--- /  ---node offline--- status in the discord side bar 
![nanoBotRequest](https://user-images.githubusercontent.com/81168316/120571988-2f04b000-c456-11eb-8954-0545ec105925.PNG)

**Comment by JohnGarnham** [comment]
For whatever weird reason, Discord only allows certain statuses for bots. The only statuses allowed for bots are in the form of:

"Playing <input>...", "Streaming <input>...", "Listening to <input>...", "Watching <input>..."

https://python.plainenglish.io/how-to-change-discord-bot-status-with-discord-py-39219c8fceea

I can work around this. Actually "Listening to ...." sort of fits. But it's a very, very weird design decision by Discord. I even double-checked with the Discord.py if there's any way to change a bot's status to something else, and I can't.

**Comment by JohnGarnham** [comment]
Updated bot to display a status like 
![image](https://user-images.githubusercontent.com/71062473/121615397-0401f980-ca1e-11eb-9013-08d11b9dc686.png)

Right now Online or Offline is just a placeholder I toggle with n!toggle_online.

We need to think of a way to implement a heartbeat to periodically check whether the node is still online or not.

Some options:
1) Send a simple RPC call [i.e. version] periodically, if it fails set status Offline otherwise keep status Online
2) A little more complicated, subscribe to websockets https://docs.nano.org/integration-guides/websockets/#keepalive

I think 1 should be fine. 






if curl -k --data '{"action": "version"}' http://127.0.0.1:7076; then    echo "success"else    # If not send the email. Be sure to insert your email here.    echo "Alert: Nano node not reachable!" | mail -s "Nano Node RPC not reachable alert!" example@example.comfi




if curl -k --data '{"action": "version"}' http://127.0.0.1:7076; then    echo "success"else    # If not send the email. Be sure to insert your email here.    echo "Alert: Nano node not reachable!" | mail -s "Nano Node RPC not reachable alert!" example@example.comfi

**Comment by Gabrielpatrola** [comment]
I see that this is already made, so I will close this issue.

Will open it if needed

**Comment by JohnGarnham** [comment]
Test
Start the nano node in docker along with the bot. Check that the node is running properly and that the bot status is Online.

Set the node offline with:
$ docker pause <nano_node>

Wait HEARTBEAT_INTERVAL seconds. Check that the bot status went to Offline.

Set the node back online with:
$ docker unpause <nano_node>

Make sure that the bot goes back to Online.

Any way to automate this and other tests??
